            lgr.info('')
            lgr.info('-------------------------- Set Configuration Smart values and operation fuzzing ----------------------\n')
            #lgr.info('\n')
            lgr.info('Set Configuration Smart values')
            lgr.info("\n".join("('{}':{})".format(k, v) for k, v in p.dict_smart_value().items()))
            #print(*p.dict_smart_value().items(), sep='\n')
            #print(*p.dict_operation().items(), sep='\n')
            #lgr.info(*p.dict_operation().items(), '\n')
            #lgr.info("Loging dict ---> {}".format(p.dict_smart_value().items(),sep='\n))
            lgr.info('')
            lgr.info('Set operation fuzzing')
            lgr.info("\n".join("('{}:{})".format(k, v) for k, v in p.dict_operation().items()))                    
            lgr.info('')
            lgr.info('---------------------------- Set Configuration for function 20,21,22 -----------------------------------')
            lgr.info('start_address start_address_records : %d' %start_address_reco )
            lgr.info('last_address last_address_records : %d' %last_address_reco)                               
            lgr.info('---------------------------------------------------------------------------------------------------------\n')
